import { Incident } from "@/types/incident";

export const incidents: Incident[] = [
  {
    id: "INC-2026-1284",
    type: "Vehicle theft",
    location: "Yelahanka New Town",
    district: "Bengaluru",
    date: "13 Jul 2026",
    time: "22:41",
    risk: "Critical",
    status: "Under investigation",
  },
  {
    id: "INC-2026-1283",
    type: "Burglary",
    location: "Hebbal",
    district: "Bengaluru",
    date: "13 Jul 2026",
    time: "21:18",
    risk: "Elevated",
    status: "Open",
  },
  {
    id: "INC-2026-1282",
    type: "Cyber fraud",
    location: "Whitefield",
    district: "Bengaluru",
    date: "13 Jul 2026",
    time: "19:32",
    risk: "Moderate",
    status: "Evidence review",
  },
  {
    id: "INC-2026-1281",
    type: "Chain snatching",
    location: "Vijayanagar",
    district: "Mysuru",
    date: "13 Jul 2026",
    time: "18:14",
    risk: "Elevated",
    status: "Open",
  },
  {
    id: "INC-2026-1280",
    type: "Public disturbance",
    location: "Kadri",
    district: "Mangaluru",
    date: "13 Jul 2026",
    time: "16:48",
    risk: "Low",
    status: "Closed",
  },
  {
    id: "INC-2026-1279",
    type: "Vehicle theft",
    location: "Rajajinagar",
    district: "Bengaluru",
    date: "13 Jul 2026",
    time: "14:21",
    risk: "Moderate",
    status: "Under investigation",
  },
];